version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      runtime-dependencies:
        applies-to: version-updates
        patterns:
          - "aiohttp"
          - "blake3"
          - "league-tools"
          - "loguru"
          - "pyzstd"
          - "urllib3"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        applies-to: version-updates
        patterns:
          - "pytest"
          - "pytest-cov"
          - "ruff"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:20"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
